development:
  adapter: postgresql
  host: postgres
  database: study_finder_development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: postgres
  database: study_finder_test
  username: postgres
  password: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>

